application:
  title: Bookshelf
  version: 0.0.1

bookshelf:
  some-number: 11
  some-text: More information

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://tai.db.elephantsql.com:5432/tdygxryv
    driver-class-name: org.postgresql.Driver
    username: tdygxryv
    password: ${PG_PASSWORD}
    hikari:
      maximum-pool-size: 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true # required for non-embedded databases
