application:
  title: @project.name@
  version: @project.version@
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile:
        - prod
        - test-prod
server:
  port: 8090
springdoc:
  api-docs:
    enabled: false
