application:
  title: '@project.name@'
  version: '@project.version@'
server:
  port: 8080

bookshelf:
  title: 'Booksheld API'
  version: 'Version 1'
  capacity: 1000
  description: 'This bookshelf has a capacity of: '
  license:
    name: 'MIT License'
    url: 'https://opensource.org/licenses/MIT'

